### ISSUE TITLE
daysConfig 自定义 marked 颜色

### ISSUE THREAD

**Issue by lynzz** [HsuanXyz/ion2-calendar#10]
想给不同日期高亮不同的颜色

下一个版本能考虑这个功能吗

**Comment by HsuanXyz** [comment]
最初有这样的设计，但是考虑到性能放弃了。我认为可以对日期配置一个cssClass选项来解决问题

**Comment by lynzz** [comment]
现只支持给 ion-header 和 ion-content 设置 cssClass, 并无法解决对不同天设置高亮，给不同天设置 cssClass, 应不会影响到性能吧

**Comment by HsuanXyz** [comment]
@lynzz 我就是这个意思，我等会就会提交代码

**Comment by HsuanXyz** [comment]
```  typescript
  this.calendarCtrl.openCalendar({
      daysConfig:[
        {
          date:new Date(2017,0,1),
          subTitle:'danger',
          marked:true,
          cssClass:'day-danger',
        }
      ],
      cssClass:'my-cal'
    })
```

``` scss
calendar-page.my-cal{

  button.day-danger {
    background-color: #e02041;
    border-radius:5px;
    &.marked p,&.marked em {
      color: #fff;
    }
  }
}
```
